# Generated by Django 5.0.7 on 2024-07-15 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="StockItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=100)),
                ("item", models.CharField(max_length=100)),
                ("less", models.DecimalField(decimal_places=2, max_digits=10)),
                ("nw", models.DecimalField(decimal_places=2, max_digits=10)),
                ("gw", models.DecimalField(decimal_places=2, max_digits=10)),
                ("pcs", models.IntegerField()),
                ("shop", models.IntegerField(choices=[(1, "Shop 1"), (2, "Shop 2")])),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="stock.category"
                    ),
                ),
            ],
        ),
    ]
