# Generated by Django 5.0.7 on 2024-07-17 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="stockitem",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stock_items",
                to="stock.category",
            ),
        ),
        migrations.AlterField(
            model_name="stockitem",
            name="gw",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="stockitem",
            name="less",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="stockitem",
            name="nw",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="stockitem",
            name="shop",
            field=models.IntegerField(),
        ),
    ]
