# Generated by Django 5.0.7 on 2024-07-19 07:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0002_alter_category_name_alter_stockitem_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockitem",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
