# Generated by Django 5.0.7 on 2024-07-28 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0003_stockitem_created_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stockitem",
            name="item",
        ),
        migrations.RemoveField(
            model_name="stockitem",
            name="shop",
        ),
        migrations.AddField(
            model_name="category",
            name="shop",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="stockitem",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
        migrations.AddField(
            model_name="stockitem",
            name="kundan",
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="stockitem",
            name="moti",
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="stockitem",
            name="po",
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
