# Generated by Django 5.0.7 on 2024-07-30 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0004_remove_stockitem_item_remove_stockitem_shop_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockitem",
            name="code",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="stockitem",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="stock_images/"),
        ),
    ]
