# Generated by Django 5.0.7 on 2024-08-28 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0005_alter_stockitem_code_alter_stockitem_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="stockitem",
            old_name="less",
            new_name="k_amount",
        ),
        migrations.AddField(
            model_name="stockitem",
            name="m_amount",
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="stockitem",
            name="p_amount",
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="stockitem",
            name="supplier",
            field=models.CharField(default=0.0, max_length=255),
            preserve_default=False,
        ),
    ]
