# Generated by Django 5.0.7 on 2024-08-28 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0006_rename_less_stockitem_k_amount_stockitem_m_amount_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="stockitem",
            old_name="k_amount",
            new_name="k_amt",
        ),
        migrations.RenameField(
            model_name="stockitem",
            old_name="m_amount",
            new_name="m_amt",
        ),
        migrations.RenameField(
            model_name="stockitem",
            old_name="p_amount",
            new_name="p_amt",
        ),
    ]
